# Prova 2 CN
Alan dantas - 202109882

In [4]:
"""
Definindo funções auxiliares para resolução da prova
"""

import numpy as np
def resol_sist_triang_inf(a, b):
    """
    Resolve um sistema de equações lineares Ax = b,
    onde A é uma matriz triangular inferior.
    Parâmetros:
    a : array_like
        Matriz dos coeficientes (triangular inferior).
    b : array_like
        Vetor dos termos independentes.
    """
    n = len(b)
    x = np.zeros(n)
    x[0] = b[0] / a[0, 0]
    for k in range(1, n):
        s = 0
        for j in range(k):
            s += a[k, j] * x[j]
        x[k] = (b[k] - s) / a[k, k]
    return x

# Método da substituição regressiva
def resol_sist_triang_sup(a, b):
    """Resolve um sistema de equações lineares Ax = b
    Parâmetros:
    a : array_like
        Matriz dos coeficientes (triangular superior).
    b : array_like
        Vetor dos termos independentes.
    """
    n = len(b)
    x = np.zeros(len(b))
    x[n-1] = b[n-1] / a[n-1,n-1]

    for k in range(n-2, -1, -1):
        s = 0
        for j in range(k+1, n):
            s += a[k,j] * x[j]
        x[k] = (b[k] - s) / a[k,k]

    return x

Questão 1

In [6]:
import numpy as np
np.set_printoptions(suppress=True)

def gauss_etapas(A, b, imprimir_m=True, imprimir_ab=True):
    A = A.astype(float).copy()
    b = b.astype(float).copy()
    n = A.shape[0]
    etapas = []  # lista de tuplas (A^{(k)}, b^{(k)})

    # A^{0} | b^{0}
    if imprimir_ab:
        print("A^{0} | b^{0} :")
        print("A^{0} :")
        print(A)
        print("b^{0} :")
        print(b)
    etapas.append((A.copy(), b.copy()))  # etapa 0

    # Etapas k = 0..n-2
    for k in range(n-1):
        piv = A[k,k]
        if abs(piv) < 1e-14:
            raise ZeroDivisionError(f"Pivô nulo na etapa {k}. Necessário pivoteamento.")

        # pivô + multiplicadores antes de imprimir A^{k+1}|b^{k+1}
        if imprimir_m:
            print("pivô")
            print(f"a[{k+1},{k+1}] = {piv:.6g}")
            print("multiplicadores")

        for i in range(k+1, n):
            m = A[i,k]/piv
            if imprimir_m:
                print(f"m[{i+1},{k+1}] = {m:.6g}")
            # aplica eliminação
            A[i,k] = 0.0
            for j in range(k+1, n):
                A[i,j] -= m*A[k,j]
            b[i] -= m*b[k]

        etapas.append((A.copy(), b.copy()))

        if imprimir_ab:
            print(f"A^{{{k+1}}} | b^{{{k+1}}} :")
            print(f"A^{{{k+1}}} :")
            print(A)
            print(f"b^{{{k+1}}} :")
            print(b)

    return etapas


def retrossubstituicao(U, y):
    n = U.shape[0]
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        s = 0.0
        for j in range(i+1, n):
            s += U[i,j]*x[j]
        x[i] = (y[i]-s)/U[i,i]
    return x

# Dados do sistema 4x4 (da imagem)
A0 = np.array([[  2,  1, -1,  3],
               [  1,  0,  2, -2],
               [  3,  2,  1,  1],
               [  0,  1,  4,  2]], dtype=float)
b0 = np.array([ 12,  0,  11, 19], dtype=float)

# Executa as etapas na ordem pedida
etapas = gauss_etapas(A0, b0, imprimir_m=True, imprimir_ab=True)

# Resolve com retrossubstituição usando a última etapa
A_final, b_final = etapas[-1]
x = retrossubstituicao(A_final, b_final)
print("Solução x:", x)

A^{0} | b^{0} :
A^{0} :
[[ 2.  1. -1.  3.]
 [ 1.  0.  2. -2.]
 [ 3.  2.  1.  1.]
 [ 0.  1.  4.  2.]]
b^{0} :
[12.  0. 11. 19.]
pivô
a[1,1] = 2
multiplicadores
m[2,1] = 0.5
m[3,1] = 1.5
m[4,1] = 0
A^{1} | b^{1} :
A^{1} :
[[ 2.   1.  -1.   3. ]
 [ 0.  -0.5  2.5 -3.5]
 [ 0.   0.5  2.5 -3.5]
 [ 0.   1.   4.   2. ]]
b^{1} :
[12. -6. -7. 19.]
pivô
a[2,2] = -0.5
multiplicadores
m[3,2] = -1
m[4,2] = -2
A^{2} | b^{2} :
A^{2} :
[[ 2.   1.  -1.   3. ]
 [ 0.  -0.5  2.5 -3.5]
 [ 0.   0.   5.  -7. ]
 [ 0.   0.   9.  -5. ]]
b^{2} :
[ 12.  -6. -13.   7.]
pivô
a[3,3] = 5
multiplicadores
m[4,3] = 1.8
A^{3} | b^{3} :
A^{3} :
[[ 2.   1.  -1.   3. ]
 [ 0.  -0.5  2.5 -3.5]
 [ 0.   0.   5.  -7. ]
 [ 0.   0.   0.   7.6]]
b^{3} :
[ 12.   -6.  -13.   30.4]
Solução x: [ 2. -1.  3.  4.]


questão 2

In [22]:
import numpy as np


A0 = np.array([
               [5, 1, -6],
               [-2, 5, 1],
               [-5, -1, -1]
               ], dtype=float)
print("A0:\n", A0)


# Multiplicadores da primeira coluna
m21 = A0[1,0] / A0[0,0]
m31 = A0[2,0] / A0[0,0]


M0 = np.array([
    [1,    0,    0],
    [-m21, 1,    0],
    [-m31, 0,    1],
], dtype=float)
print("M0:\n", M0)


A1 = M0 @ A0
print("A1:\n", A1)


# Multiplicador da segunda coluna (linha 3, 4 e 5, coluna 2)
m32 = A1[2,1] / A1[1,1]


M1 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, -m32, 1],
], dtype=float)
print("M1:\n", M1)

A2 = M1 @ A1 # A2 é a U
print("A2:\n", A2)

L = np.array([
    [1,    0,    0],
    [m21,  1,    0],
    [m31, m32,   1],
], dtype=float)
print("L:\n", L)

# Vetor b do enunciado (3)
b = np.array([-20, -11, -6], dtype=float)
print("b:", b)

L @ A2  # Deve ser igual a A0


y = resol_sist_triang_inf(L, b)
print("Ly=b")
print("y=", np.round(y, 7))
x = resol_sist_triang_sup(A2, y)  # A2 é o U
print("Ux=y")
print(f"A solucao do sistema linear é:")
print("x=", np.round(x, 7))

#verificação final
print("||L@A2 - A0|| (deve ser igual a A0):", np.linalg.norm(L @ A2 - A0))

A0:
 [[ 5.  1. -6.]
 [-2.  5.  1.]
 [-5. -1. -1.]]
M0:
 [[1.  0.  0. ]
 [0.4 1.  0. ]
 [1.  0.  1. ]]
A1:
 [[ 5.   1.  -6. ]
 [ 0.   5.4 -1.4]
 [ 0.   0.  -7. ]]
M1:
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
A2:
 [[ 5.   1.  -6. ]
 [ 0.   5.4 -1.4]
 [ 0.   0.  -7. ]]
L:
 [[ 1.   0.   0. ]
 [-0.4  1.   0. ]
 [-1.   0.   1. ]]
b: [-20. -11.  -6.]
Ly=b
y= [-20. -19. -26.]
Ux=y
A solucao do sistema linear é:
x= [ 0.968254 -2.555556  3.714286]
||L@A2 - A0|| (deve ser igual a A0): 0.0


Questão 3

In [ ]:
import numpy as np
import math

# tem que ser simétrica definida positiva
def cholesky_slide(A):
    """
    Fatoração de Cholesky (seguindo o slide)
    ----------
    A : ndarray (n x n)
        Matriz simétrica definida positiva.
    Retorno
    -------
    G : ndarray (n x n)
        Matriz triangular inferior tal que A = G @ G.T
    """
    A = np.array(A, dtype=float)
    n = A.shape[0]
    G = np.zeros_like(A)
    # Passo 1: g11
    G[0,0] = math.sqrt(A[0,0])
    # Passo 2: primeira coluna (i = 2..n no slide -> i=1..n-1 em Python)
    for i in range(1, n):
        G[i,0] = A[i,0] / G[0,0]
    # Passo 3: colunas k = 2..n-1  (slide) => k = 1..n-2 (Python)
    for k in range(1, n-1):
        # soma = sum_{j=1}^{k-1} g_{k,j}^2  (slide, j=1..k-1) -> j=0..k-1 em Python
        soma = 0.0
        for j in range(0, k):
            soma += G[k,j]**2
        r = A[k,k] - soma
        if r <= 0:
            raise ValueError(f"Matriz não é definida positiva (r={r} <= 0) na posição k={k}.")
        G[k,k] = math.sqrt(r)
        # Linhas i = k+1..n  -> i = k+1..n-1
        for i in range(k+1, n):
            soma = 0.0
            for j in range(0, k):
                soma += G[i,j] * G[k,j]
            G[i,k] = (A[i,k] - soma)/G[k,k]
    # Passo 4: última linha g_nn
    soma = 0.0
    for j in range(0, n-1):
        soma += G[n-1, j]**2
    r = A[n-1, n-1] - soma
    if r <= 0:
        raise ValueError(f"Matriz não é definida positiva (r={r} <= 0) na última etapa.")
    G[n-1, n-1] = math.sqrt(r)
    return G

# -------------------------------------------------
# Questão 3 (Cholesky)
# -------------------------------------------------
A = np.array([
    [ 6.,  2., 1.,  0., 0.],
    [  2.,   5., 2.,   1., 0.],
    [  1.,   2., 6.,  2., 1.],
    [  0.,   1., 2.,   5., 2.],
    [  0.,   0., 1.,   2., 4.]
], dtype=float)
print("Matriz A =\n", A)

b = np.array([  -52.,  4., -5., 18., 8.], dtype=float)
print("Vetor b =", b)
# (a) Fatoração de Cholesky A = G G^T
G = cholesky_slide(A)
print("3a)(matriz G e) G =\n", G)
print("3a) (matriz G transporta e) G^T =\n", G.T)
print("verificação: ||A - G G^T||_inf =", np.max(np.abs(A - G @ G.T)))

# (b) Resolver Gy = b (substituição progressiva)
y = resol_sist_triang_inf(G, b)
print("3b) y (solução de Gy=b) =", y)

# (c) Resolver G^T x = y (substituição regressiva)
x = resol_sist_triang_sup(G.T, y)
print("3c) x (solução final) =", x)

# Checagens explicadas (o que deve acontecer)
print("\nChecagens — o que verificar e o esperado")
tol = 1e-10

# 2) Sistema inferior: Gy ≈ b
res1 = np.max(np.abs(G @ y - b))
print("\n2) Substituição progressiva (Gy = b):")
print("   max|Gy - b| =", res1, "(esperado: ~0)")
print("   Gy =", G @ y)
print("   b  =", b)
print("   Interpretação: Gy e b devem coincidir (diferença só por arredondamento).")

# 3) Sistema superior: G^T x ≈ y
res2 = np.max(np.abs(G.T @ x - y))
print("\n3) Substituição regressiva (G^T x = y):")
print("   max|G^T x - y| =", res2, "(esperado: ~0)")
print("   G^T x =", G.T @ x)
print("   y     =", y)
print("   Interpretação: G^T x e y devem coincidir (diferença só por arredondamento).")

Matriz A =
 [[6. 2. 1. 0. 0.]
 [2. 5. 2. 1. 0.]
 [1. 2. 6. 2. 1.]
 [0. 1. 2. 5. 2.]
 [0. 0. 1. 2. 4.]]
Vetor b = [-52.   4.  -5.  18.   8.]
3a)(matriz G e) G =
 [[2.44949  0.       0.       0.       0.      ]
 [0.816497 2.081666 0.       0.       0.      ]
 [0.408248 0.800641 2.278664 0.       0.      ]
 [0.       0.480384 0.708918 2.065591 0.      ]
 [0.       0.       0.438854 0.81763  1.771691]]
3a) (matriz G transporta e) G^T =
 [[2.44949  0.816497 0.408248 0.       0.      ]
 [0.       2.081666 0.800641 0.480384 0.      ]
 [0.       0.       2.278664 0.708918 0.438854]
 [0.       0.       0.       2.065591 0.81763 ]
 [0.       0.       0.       0.       1.771691]]
verificação: ||A - G G^T||_inf = 8.881784197001252e-16
3b) y (solução de Gy=b) = [-21.228911  10.248202  -1.991721   7.014403   1.771691]
3c) x (solução final) = [-10.   5.  -2.   3.   1.]

Checagens — o que verificar e o esperado
1) Fatoração A = G G^T:
   ||A - G G^T||_inf = 8.881784197001252e-16 (esperado: muito próxi

Questão 4

In [ ]:
#a) Verificação de dominância diagonal (por linha)
import numpy as np
np.set_printoptions(suppress=True)

# Dados do exercício (A, b)
A = np.array([
    [ 10.,  -2., 0.,  -1., 0],
    [  1., 5.,  2.,  0., 1.],
    [  0.,  3., 6., -2., 0.],
    [  0.,  0., 3., 7., 2.],
    [  1.,  -1., 0., 5., 10.]
], dtype=float)

b = np.array([2, -11, -27, 29], dtype=float)

# (a) Verificação de dominância diagonal (por linha)
row_sums = np.sum(np.abs(A), axis=1) - np.abs(np.diag(A))
alpha = row_sums / np.abs(np.diag(A))
print("alphas por linha (alpha1, alpha 2, etc..):", alpha)
print("max(alpha) =", np.max(alpha))
print("Estritamente dominante por linha? ", np.all(np.abs(np.diag(A)) > row_sums))


alphas por linha (alpha1, alpha 2, etc..): [0.3      0.8      0.833333 0.714286 0.7     ]
max(alpha) = 0.8333333333333334
Estritamente dominante por linha?  True


True

In [ ]:
#Método de Gauss–Jacobi

# ----------------------------------------------
# MÉTODO DE GAUSS–JACOBI
# ----------------------------------------------
# Critério de parada: d = max |x^(k) − x^(k−1)| < 0,001
# Chute inicial: x^(0) = (1,1,1,1)
# ----------------------------------------------

# Precisão desejada (erro máximo permitido)
e = 1e-4 # 0.0001

# Chute inicial
x0 = np.array([[1.0],
               [1.0],
               [1.0],
               [1.0],
               [1.0]])

# Matriz dos coeficientes A (4x4)
A = np.array([
    [ 10.,  -2., 0.,  -1., 0],
    [  1., 5.,  2.,  0., 1.],
    [  0.,  3., 6., -2., 0.],
    [  0.,  0., 3., 7., 2.],
    [  1.,  -1., 0., 5., 10.]
], dtype=float)

# Vetor de termos independentes B (4x1)
B = np.array([
    [-31.],
    [-3.],
    [-32.],
    [ 12.],
    [ 102.]
], dtype=float)

print("Matriz A:")
print(A)
print("\nVetor B:")
print(B)
print("\nChute inicial x0:")
print(x0)

print("\nInício do método de Gauss–Jacobi:\n")

# Número de variáveis (tamanho do sistema)
n = len(B)

# Vetores para armazenar os valores atuais e os anteriores
x_ant = x0.copy()
x_novo = np.zeros_like(x_ant)

# Contador de iterações
k = 0

# Loop principal — repete até a diferença entre iterações ser pequena
while True:
    k += 1  # conta a iteração atual
    
    # Calcula cada componente x_i
    for i in range(n):
        soma = 0
        
        # Soma dos termos A[i][j] * x_ant[j], exceto j = i
        for j in range(n):
            if j != i:
                soma += A[i][j] * x_ant[j]
        
        # Fórmula do método de Jacobi
        x_novo[i] = (B[i] - soma) / A[i][i]
    
    # Calcula o erro (diferença máxima entre iterações)
    erro = np.max(np.abs(x_novo - x_ant))
    
    # Mostra o progresso de cada iteração (6 casas)
    print(f"Iteração {k}: x = {x_novo.ravel()}, erro = {erro:.6f}")
    
    # Verifica o critério de parada
    if erro < e:
        break
    
    # Atualiza o vetor anterior
    x_ant = x_novo.copy()

# Exibe o resultado final
print("\nSolução aproximada encontrada:")
print(x_novo)
print(f"Número total de iterações: {k}")

Matriz A:
[[10. -2.  0. -1.  0.]
 [ 1.  5.  2.  0.  1.]
 [ 0.  3.  6. -2.  0.]
 [ 0.  0.  3.  7.  2.]
 [ 1. -1.  0.  5. 10.]]

Vetor B:
[[-31.]
 [ -3.]
 [-32.]
 [ 12.]
 [102.]]

Chute inicial x0:
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]

Início do método de Gauss–Jacobi:

Iteração 1: x = [-2.8 -1.4 -5.5  1.   9.7], erro = 8.700000
Iteração 2: x = [-3.28  0.22 -4.3   1.3   9.84], erro = 1.620000
Iteração 3: x = [-2.926    -0.192    -5.01      0.745714  9.9     ], erro = 0.710000
Iteração 4: x = [-3.063829  0.0092   -4.988762  1.032857 10.100543], erro = 0.287143
Iteração 5: x = [-2.994874 -0.011838 -4.993648  0.966457  9.990874], erro = 0.109669
Iteração 6: x = [-3.005722 -0.001741 -5.005262  0.999885 10.015075], erro = 0.033428
Iteração 7: x = [-3.00036   0.000234 -4.999168  0.997948 10.000456], erro = 0.014619
Iteração 8: x = [-3.000158 -0.000352 -5.000801  0.999513 10.001085], erro = 0.001633
Iteração 9: x = [-3.000119  0.000135 -4.999986  1.000033 10.000224], erro = 0.000861
Iteração 10: x = 

: 

In [31]:
#Método de Gauss–Seidel
# Gauss–Seidel Method
import numpy as np
np.set_printoptions(precision=6, suppress=True)

# Precisão desejada (erro máximo permitido)
e = 1e-4 # 0.0001

# Chute inicial (4x1)
x = np.array([[1.0],
              [1.0],
              [1.0],
              [1.0],
              [1.0]])

# Matriz dos coeficientes A (4x4)
A = np.array([
    [ 10.,  -2., 0.,  -1., 0],
    [  1., 5.,  2.,  0., 1.],
    [  0.,  3., 6., -2., 0.],
    [  0.,  0., 3., 7., 2.],
    [  1.,  -1., 0., 5., 10.]
], dtype=float)

# Vetor de termos independentes B (4x1)
B = np.array([
    [-31.],
    [-3.],
    [-32.],
    [ 12.],
    [ 102.]
], dtype=float)

# Número de variáveis (tamanho do sistema)
n = len(B)

# Contador de iterações
k = 0

while True:
    k += 1  
    x_ant = x.copy()
    
    for i in range(n):
        soma = 0.0
        
        for j in range(n):
            if j != i:
                soma += A[i][j] * x[j]  # usa valores já atualizados quando j<i
        
        x[i] = (B[i] - soma) / A[i][i]
    
    erro = np.max(np.abs(x - x_ant))
    
    print(f"Iteração {k}: x = {x.ravel()}, erro = {erro:.6f}")
    
    # Verifica o critério de parada
    if erro < e:
        break
    
# Exibe o resultado final
print("\nSolução aproximada encontrada:")
print(x)
print(f"Número total de iterações: {k}")

Iteração 1: x = [-2.8      -0.64     -4.68      3.434286  8.698857], erro = 7.698857
Iteração 2: x = [-2.884571  0.109143 -4.243143  1.047388  9.975678], erro = 2.386898
Iteração 3: x = [-2.973433 -0.303192 -4.832608  0.93521   9.999419], erro = 0.589465
Iteração 4: x = [-3.067117 -0.053417 -4.994888  0.997975 10.002382], erro = 0.249775
Iteração 5: x = [-3.010886 -0.000344 -5.000503  0.999535 10.001287], erro = 0.056231
Iteração 6: x = [-3.000115 -0.000033 -5.000138  0.999692 10.000162], erro = 0.010771
Iteração 7: x = [-3.000037  0.00003  -5.000118  1.000004 10.000005], erro = 0.000312
Iteração 8: x = [-2.999994  0.000045 -5.000021  1.000008 10.      ], erro = 0.000097

Solução aproximada encontrada:
[[-2.999994]
 [ 0.000045]
 [-5.000021]
 [ 1.000008]
 [10.      ]]
Número total de iterações: 8
