In [2]:
import numpy as np

def resol_sist_triang(a, b):
    """Resolve um sistema de equações lineares Ax = b
    Parâmetros:
    a : array_like
        Matriz dos coeficientes (triangular superior).
    b : array_like
        Vetor dos termos independentes.
    """
    n = len(b)
    x = np.zeros(len(b))
    x[n-1] = b[n-1] / a[n-1,n-1]

    for k in range(n-2, -1, -1):
        s = 0
        for j in range(k+1, n):
            s += a[k,j] * x[j]
        x[k] = (b[k] - s) / a[k,k]

    return x


In [ ]:
#ex01 LRU
import numpy as np

A0 = np.array([[3, 2, 4],
               [1, 1, 2],
               [4, 3, -2]], dtype=float)
print("A0:\n", A0)

# Multiplicadores da primeira coluna
m21 = A0[1,0] / A0[0,0]
m31 = A0[2,0] / A0[0,0]

M0 = np.array([[1, 0, 0],
               [-m21, 1, 0],
               [-m31, 0, 1]], dtype=float)

print("M0:\n", M0)

B = np.array([[1],
              [2],
              [3]], dtype=float)

C = M0 @ B
print("C:\n", C)

A1 = M0 @ A0
print("A1:\n", A1)
# print("A1:\n", A1)

# Multiplicador da segunda coluna (linha 3, coluna 2)
m32 = A1[2,1] / A1[1,1]

M1 = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, -m32, 1]], dtype=float)

D = M1 @ C
print("D:\n", D)

A2 = M1 @ A1
# print("A2:\n", A2)

L = np.array([[1, 0, 0],
              [m21, 1, 0],
              [m31, m32, 1]], dtype=float)
# print("L:\n", L)

L @ A2  # Deve resultar em A0
print("L @ A2:\n", L @ A2)
print("A2:\n", A2)

x = resol_sist_triang(A2, D.flatten())
print("Sol:", x)


A0:
 [[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3. -2.]]
M0:
 [[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]
C:
 [[1.        ]
 [1.66666667]
 [1.66666667]]
A1:
 [[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -7.33333333]]
D:
 [[ 1.00000000e+00]
 [ 1.66666667e+00]
 [-4.44089210e-16]]
L @ A2:
 [[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3. -2.]]
A2:
 [[ 3.00000000e+00  2.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  3.33333333e-01  6.66666667e-01]
 [ 0.00000000e+00  5.55111512e-17 -8.00000000e+00]]
Sol: [-3.00000000e+00  5.00000000e+00  5.55111512e-17]


In [ ]:
A = np.array([[3, 2, 4],
              [0, 1/3, 2/3],
              [0, 0, -8]], dtype=float)

b = np.array([1, 5/3, 0], dtype=float)
x = resol_sist_triang(A, b)
print("Sol:", x)

Sol: [-3.  5. -0.]
6.05576195e-17


In [3]:
#ex02 LRU
import numpy as np

A0 = np.array([[3, -2, 1],
               [1, 2, -1],
               [2, 1, 3]], dtype=float)
print("A0:\n", A0)

# Multiplicadores da primeira coluna
m21 = A0[1,0] / A0[0,0]
m31 = A0[2,0] / A0[0,0]

M0 = np.array([[1, 0, 0],
               [-m21, 1, 0],
               [-m31, 0, 1]], dtype=float)

print("M0:\n", M0)

B = np.array([[9],
              [-5],
              [6]], dtype=float)

C = M0 @ B
print("C:\n", C)

A1 = M0 @ A0
print("A1:\n", A1)
# print("A1:\n", A1)

# Multiplicador da segunda coluna (linha 3, coluna 2)
m32 = A1[2,1] / A1[1,1]

M1 = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, -m32, 1]], dtype=float)

D = M1 @ C
print("D:\n", D)

A2 = M1 @ A1
# print("A2:\n", A2)

L = np.array([[1, 0, 0],
              [m21, 1, 0],
              [m31, m32, 1]], dtype=float)
# print("L:\n", L)

L @ A2  # Deve resultar em A0
print("L @ A2:\n", L @ A2)
print("A2:\n", A2)

x = resol_sist_triang(A2, D.flatten())
print("Sol:", x)
# tem que dar (1, -2, 2)


A0:
 [[ 3. -2.  1.]
 [ 1.  2. -1.]
 [ 2.  1.  3.]]
M0:
 [[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-0.66666667  0.          1.        ]]
C:
 [[ 9.]
 [-8.]
 [ 0.]]
A1:
 [[ 3.         -2.          1.        ]
 [ 0.          2.66666667 -1.33333333]
 [ 0.          2.33333333  2.33333333]]
D:
 [[ 9.]
 [-8.]
 [ 7.]]
L @ A2:
 [[ 3. -2.  1.]
 [ 1.  2. -1.]
 [ 2.  1.  3.]]
A2:
 [[ 3.         -2.          1.        ]
 [ 0.          2.66666667 -1.33333333]
 [ 0.          0.          3.5       ]]
Sol: [ 1. -2.  2.]


In [ ]:
import numpy as np

A0 = np.array([[2, -3, 4, 5, -6],
               [1, 2, -1, 3, 4],
               [3, -4, 1, 2, -1],
               [5, 2, -2, 4, 3],
               [-2, 3, 2, -1, 5]], dtype=float)
print("A0:\n", A0)

# Multiplicadores da primeira coluna
m21 = A0[1,0] / A0[0,0]
m31 = A0[2,0] / A0[0,0]
m41 = A0[3,0] / A0[0,0]
m51 = A0[4,0] / A0[0,0]

M0 = np.array([
    [1,    0,    0,    0,    0],
    [-m21, 1,    0,    0,    0],
    [-m31, 0,    1,    0,    0],
    [-m41, 0,    0,    1,    0],
    [-m51, 0,    0,    0,    1]
], dtype=float)
B = np.array([[-21],
              [29],
              [-2],
              [30],
              [24]], dtype=float)
A1 = M0 @ A0
# print("A1:\n", A1)
C = M0 @ B
print("C:\n", C)

# Multiplicador da segunda coluna (linha 3, coluna 2)
m32 = A1[2,1] / A1[1,1]
m42 = A1[3,1] / A1[1,1]
m52 = A1[4,1] / A1[1,1]

M1 = np.array([
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, -m32, 1, 0, 0],
    [0, -m42, 0, 1, 0],
    [0, -m52, 0, 0, 1]
], dtype=float)

A2 = M1 @ A1
D = M1 @ C
print("D:\n", D)
# print("A2:\n", A2)

# Multiplicador da terceira coluna (linha 3, coluna 2)
m43 = A2[3,2] / A2[2,2]
m53 = A2[4,2] / A2[2,2]

M2 = np.array([
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, -m43, 1, 0],
    [0, 0, -m53, 0, 1]
], dtype=float)

A3 = M2 @ A2
E = M2 @ D
print("E:\n", E)
# print("A2:\n", A2)

# Multiplicador da quarta coluna (linha 5, coluna 4)
m54 = A3[4,3] / A3[3,3]

M3 = np.array([
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, -m54, 1]
], dtype=float)

A4 = M3 @ A3
F = M3 @ E
print("E:\n", E)

L = np.array([
    [1,    0,    0,    0,    0],
    [m21,  1,    0,    0,    0],
    [m31, m32,   1,    0,    0],
    [m41, m42, m43,    1,    0],
    [m51, m52, m53, m54,    1]
], dtype=float)
# print("L:\n", L)

L @ A4  # Deve resultar em A0
print("L @ A4:\n", L @ A4)

#Ux=d
x = resol_sist_triang(A4, F.flatten())
print("Sol:", x)
#tem que dar (1, 1, 0, 2, 5)


A0:
 [[ 2. -3.  4.  5. -6.]
 [ 1.  2. -1.  3.  4.]
 [ 3. -4.  1.  2. -1.]
 [ 5.  2. -2.  4.  3.]
 [-2.  3.  2. -1.  5.]]
C:
 [[-21. ]
 [ 39.5]
 [ 29.5]
 [ 82.5]
 [  3. ]]
D:
 [[-21.        ]
 [ 39.5       ]
 [ 23.85714286]
 [-24.71428571]
 [  3.        ]]
E:
 [[-21.        ]
 [ 39.5       ]
 [ 23.85714286]
 [-44.84375   ]
 [ 34.3125    ]]
E:
 [[-21.        ]
 [ 39.5       ]
 [ 23.85714286]
 [-44.84375   ]
 [ 34.3125    ]]
L @ A4:
 [[ 2. -3.  4.  5. -6.]
 [ 1.  2. -1.  3.  4.]
 [ 3. -4.  1.  2. -1.]
 [ 5.  2. -2.  4.  3.]
 [-2.  3.  2. -1.  5.]]
Sol: [ 1.  1. -0.  2.  5.]


: 