# Método da fatoração LU

In [ ]:
import numpy as np

A0 = np.array([[3, 2, 4],
               [1, 1, 2],
               [4, 3, -2]], dtype=float)
print("A0:\n", A0)

# Multiplicadores da primeira coluna
m21 = A0[1,0] / A0[0,0]
m31 = A0[2,0] / A0[0,0]

M0 = np.array([[1, 0, 0],
               [-m21, 1, 0],
               [-m31, 0, 1]], dtype=float)

print("M0:\n", M0)

A1 = M0 @ A0
# print("A1:\n", A1)

# Multiplicador da segunda coluna (linha 3, coluna 2)
m32 = A1[2,1] / A1[1,1]

M1 = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, -m32, 1]], dtype=float)

A2 = M1 @ A1
# print("A2:\n", A2)

L = np.array([[1, 0, 0],
              [m21, 1, 0],
              [m31, m32, 1]], dtype=float)
# print("L:\n", L)

L @ A2  # Deve resultar em A0
print("L @ A2:\n", L @ A2)


A0:
 [[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3. -2.]]
M0:
 [[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]
L @ A2:
 [[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3. -2.]]


In [ ]:
import numpy as np

A0 = np.array([[3, 2, 4],
               [1, 1, 2],
               [4, 3, -2]], dtype=float)
print("A0:\n", A0)

# Multiplicadores da primeira coluna
m21 = A0[1,0] / A0[0,0]
m31 = A0[2,0] / A0[0,0]

M0 = np.array([[1, 0, 0],
               [-m21, 1, 0],
               [-m31, 0, 1]], dtype=float)

print("M0:\n", M0)

B = np.array([[1],
              [2],
              [3]], dtype=float)

C = M0 @ B
print("C:\n", C)

D = M1 @ C
print("D:\n", D)

A1 = M0 @ A0
print("A1:\n", A1)
# print("A1:\n", A1)

# Multiplicador da segunda coluna (linha 3, coluna 2)
m32 = A1[2,1] / A1[1,1]

M1 = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, -m32, 1]], dtype=float)

A2 = M1 @ A1
# print("A2:\n", A2)

L = np.array([[1, 0, 0],
              [m21, 1, 0],
              [m31, m32, 1]], dtype=float)
# print("L:\n", L)

L @ A2  # Deve resultar em A0
print("L @ A2:\n", L @ A2)


A0:
 [[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3. -2.]]
M0:
 [[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]
C:
 [[1.        ]
 [1.66666667]
 [1.66666667]]
D:
 [[ 1.00000000e+00]
 [ 1.66666667e+00]
 [-4.44089210e-16]]
A1:
 [[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -7.33333333]]
L @ A2:
 [[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3. -2.]]


: 

In [ ]:

L @ A2  # Deve resultar em A0
print("L @ A2:\n", L @ A2)


In [1]:
import numpy as np

A0 = np.array([[2, -3, 4, 5, -6],
               [1, 2, -1, 3, 4],
               [3, -4, 1, 2, -1],
               [5, 2, -2, 4, 3],
               [-2, 3, 2, -1, 5]], dtype=float)
print("A0:\n", A0)

# Multiplicadores da primeira coluna
m21 = A0[1,0] / A0[0,0]
m31 = A0[2,0] / A0[0,0]
m41 = A0[3,0] / A0[0,0]
m51 = A0[4,0] / A0[0,0]

M0 = np.array([
    [1,    0,    0,    0,    0],
    [-m21, 1,    0,    0,    0],
    [-m31, 0,    1,    0,    0],
    [-m41, 0,    0,    1,    0],
    [-m51, 0,    0,    0,    1]
], dtype=float)

A1 = M0 @ A0
# print("A1:\n", A1)

# Multiplicador da segunda coluna (linha 3, coluna 2)
m32 = A1[2,1] / A1[1,1]
m42 = A1[3,1] / A1[1,1]
m52 = A1[4,1] / A1[1,1]

M1 = np.array([
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, -m32, 1, 0, 0],
    [0, -m42, 0, 1, 0],
    [0, -m52, 0, 0, 1]
], dtype=float)

A2 = M1 @ A1
# print("A2:\n", A2)

# Multiplicador da terceira coluna (linha 3, coluna 2)
m43 = A2[3,2] / A2[2,2]
m53 = A2[4,2] / A2[2,2]

M2 = np.array([
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, -m43, 1, 0],
    [0, 0, -m53, 0, 1]
], dtype=float)

A3 = M2 @ A2
# print("A2:\n", A2)

# Multiplicador da quarta coluna (linha 5, coluna 4)
m54 = A3[4,3] / A3[3,3]

M3 = np.array([
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, -m54, 1]
], dtype=float)

A4 = M3 @ A3

L = np.array([
    [1,    0,    0,    0,    0],
    [m21,  1,    0,    0,    0],
    [m31, m32,   1,    0,    0],
    [m41, m42, m43,    1,    0],
    [m51, m52, m53, m54,    1]
], dtype=float)
# print("L:\n", L)

L @ A4  # Deve resultar em A0
print("L @ A4:\n", L @ A4)


A0:
 [[ 2. -3.  4.  5. -6.]
 [ 1.  2. -1.  3.  4.]
 [ 3. -4.  1.  2. -1.]
 [ 5.  2. -2.  4.  3.]
 [-2.  3.  2. -1.  5.]]
L @ A4:
 [[ 2. -3.  4.  5. -6.]
 [ 1.  2. -1.  3.  4.]
 [ 3. -4.  1.  2. -1.]
 [ 5.  2. -2.  4.  3.]
 [-2.  3.  2. -1.  5.]]
