# Método da fatoração LU

In [17]:
import numpy as np
def resol_sist_triang_inf(a, b):
    """
    Resolve um sistema de equações lineares Ax = b,
    onde A é uma matriz triangular inferior.
    Parâmetros:
    a : array_like
        Matriz dos coeficientes (triangular inferior).
    b : array_like
        Vetor dos termos independentes.
    """
    n = len(b)
    x = np.zeros(n)
    x[0] = b[0] / a[0, 0]
    for k in range(1, n):
        s = 0
        for j in range(k):
            s += a[k, j] * x[j]
        x[k] = (b[k] - s) / a[k, k]
    return x

# Exemplo de uso
A = np.array([[1, 0, 0],
              [2, 1, 0],
              [2, -3, 1]], dtype=float)

b = np.array([-3, -1, -23], dtype=float)
x = resol_sist_triang_inf(A, b)
print("Sol:", x)

Sol: [-3.  5. -2.]


In [18]:
import numpy as np

def resol_sist_triang(a, b):
    """Resolve um sistema de equações lineares Ax = b
    Parâmetros:
    a : array_like
        Matriz dos coeficientes (triangular superior).
    b : array_like
        Vetor dos termos independentes.
    """
    n = len(b)
    x = np.zeros(len(b))
    x[n-1] = b[n-1] / a[n-1,n-1]

    for k in range(n-2, -1, -1):
        s = 0
        for j in range(k+1, n):
            s += a[k,j] * x[j]
        x[k] = (b[k] - s) / a[k,k]

    return x


In [ ]:
import numpy as np


A0 = np.array([[5, 1, -6, 3, 3],
               [-2, 5, 1, -1, 2],
               [-5, -1, -1, 2, -1],
               [1, 2, 3, -4, -3],
               [0, 1, 0, -3, -4]], dtype=float)
print("A0:\n", A0)


# Multiplicadores da primeira coluna
m21 = A0[1,0] / A0[0,0]
m31 = A0[2,0] / A0[0,0]
m41 = A0[3,0] / A0[0,0]
m51 = A0[4,0] / A0[0,0]


M0 = np.array([
    [1,    0,    0,    0,    0],
    [-m21, 1,    0,    0,    0],
    [-m31, 0,    1,    0,    0],
    [-m41, 0,    0,    1,    0],
    [-m51, 0,    0,    0,    1]
], dtype=float)
print("M0:\n", M0)


A1 = M0 @ A0
print("A1:\n", A1)


# Multiplicador da segunda coluna (linha 3, 4 e 5, coluna 2)
m32 = A1[2,1] / A1[1,1]
m42 = A1[3,1] / A1[1,1]
m52 = A1[4,1] / A1[1,1]


M1 = np.array([
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, -m32, 1, 0, 0],
    [0, -m42, 0, 1, 0],
    [0, -m52, 0, 0, 1]
], dtype=float)
print("M1:\n", M1)




A2 = M1 @ A1
print("A2:\n", A2)


# Multiplicador da terceira coluna (linhas 4 e 5, coluna 3)
m43 = A2[3,2] / A2[2,2]
m53 = A2[4,2] / A2[2,2]


M2 = np.array([
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, -m43, 1, 0],
    [0, 0, -m53, 0, 1]
], dtype=float)
print("M2:\n", M2)


A3 = M2 @ A2
print("A3:\n", A3)

# Multiplicador da quarta coluna (linha 5, coluna 4)
m54 = A3[4,3] / A3[3,3]


M3 = np.array([
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, -m54, 1]
], dtype=float)
print("M3:\n", M3)




A4 = M3 @ A3  # U
print("A4 (U):\n", A4)


L = np.array([
    [1,    0,    0,    0,    0],
    [m21,  1,    0,    0,    0],
    [m31, m32,   1,    0,    0],
    [m41, m42, m43,    1,    0],
    [m51, m52, m53, m54,    1]
], dtype=float)
print("L:\n", L)


# Vetor b do enunciado (5x5)
b = np.array([7.4, -3.4, 7.6, -15, -13.4], dtype=float)
print("b:", b)


y = resol_sist_triang_inf(L, b)
print("Ly=b")
print("y=", np.round(y, 7))
x = resol_sist_triang(A4, y)  # A4 é o U
print("Ux=y")
print(f"A solucao do sistema linear é:")
print("x=", np.round(x, 7))


# Verificações finais
print("||A0@x - b|| (deve ser ~0):", np.linalg.norm(A0 @ x - b))

A0:
 [[ 5.  1. -6.  3.  3.]
 [-2.  5.  1. -1.  2.]
 [-5. -1. -1.  2. -1.]
 [ 1.  2.  3. -4. -3.]
 [ 0.  1.  0. -3. -4.]]
M0:
 [[ 1.   0.   0.   0.   0. ]
 [ 0.4  1.   0.   0.   0. ]
 [ 1.   0.   1.   0.   0. ]
 [-0.2  0.   0.   1.   0. ]
 [-0.   0.   0.   0.   1. ]]
A1:
 [[ 5.   1.  -6.   3.   3. ]
 [ 0.   5.4 -1.4  0.2  3.2]
 [ 0.   0.  -7.   5.   2. ]
 [ 0.   1.8  4.2 -4.6 -3.6]
 [ 0.   1.   0.  -3.  -4. ]]
M1:
 [[ 1.          0.          0.          0.          0.        ]
 [ 0.          1.          0.          0.          0.        ]
 [ 0.         -0.          1.          0.          0.        ]
 [ 0.         -0.33333333  0.          1.          0.        ]
 [ 0.         -0.18518519  0.          0.          1.        ]]
A2:
 [[ 5.          1.         -6.          3.          3.        ]
 [ 0.          5.4        -1.4         0.2         3.2       ]
 [ 0.          0.         -7.          5.          2.        ]
 [ 0.          0.          4.66666667 -4.66666667 -4.66666667]
 [ 0.    