# Exercício 4 — Gauss–Jacobi e Gauss–Seidel
Vamos resolver o sistema do enunciado usando ambos os métodos e verificar a dominância diagonal. Critério: d = max |x_i^(k) − x_i^(k−1)| < 0,001; chute inicial x^(0) = (1,1,1,1); resultados com 6 casas.

In [1]:
#a) Verificação de dominância diagonal (por linha)
import numpy as np
np.set_printoptions(suppress=True)

# Dados do exercício (A, b)
A = np.array([
    [ 5, -2,  0, -1],
    [ 1,  8,  2,  0],
    [ 0,  3,  7, -2],
    [ 0,  0,  3,  7]
], dtype=float)

b = np.array([2, -11, -27, 29], dtype=float)

# (a) Verificação de dominância diagonal (por linha)
row_sums = np.sum(np.abs(A), axis=1) - np.abs(np.diag(A))
alpha = row_sums / np.abs(np.diag(A))
print("alphas por linha (alpha1, alpha 2, etc..):", alpha)
print("max(alpha) =", np.max(alpha))
print("Estritamente dominante por linha? ", np.all(np.abs(np.diag(A)) > row_sums))


alphas por linha (alpha1, alpha 2, etc..): [0.6        0.375      0.71428571 0.42857143]
max(alpha) = 0.7142857142857143
Estritamente dominante por linha?  True


In [2]:
#b) Método de Gauss–Jacobi
import numpy as np
np.set_printoptions(precision=6, suppress=True)

# ----------------------------------------------
# MÉTODO DE GAUSS–JACOBI
# ----------------------------------------------
# Critério de parada: d = max |x^(k) − x^(k−1)| < 0,001
# Chute inicial: x^(0) = (1,1,1,1)
# Sistema do enunciado (4x4)
# ----------------------------------------------

# Precisão desejada (erro máximo permitido)
e = 1e-3

# Chute inicial
x0 = np.array([[1.0],
               [1.0],
               [1.0],
               [1.0]])

# Matriz dos coeficientes A (4x4)
A = np.array([
    [ 5., -2.,  0., -1.],
    [ 1.,  8.,  2.,  0.],
    [ 0.,  3.,  7., -2.],
    [ 0.,  0.,  3.,  7.]
], dtype=float)

# Vetor de termos independentes B (4x1)
B = np.array([
    [  2.],
    [-11.],
    [-27.],
    [ 29.]
], dtype=float)

print("Matriz A:")
print(A)
print("\nVetor B:")
print(B)
print("\nChute inicial x0:")
print(x0)

print("\nInício do método de Gauss–Jacobi:\n")

# Número de variáveis (tamanho do sistema)
n = len(B)

# Vetores para armazenar os valores atuais e os anteriores
x_ant = x0.copy()
x_novo = np.zeros_like(x_ant)

# Contador de iterações
k = 0

# Loop principal — repete até a diferença entre iterações ser pequena
while True:
    k += 1  # conta a iteração atual
    
    # Calcula cada componente x_i
    for i in range(n):
        soma = 0
        
        # Soma dos termos A[i][j] * x_ant[j], exceto j = i
        for j in range(n):
            if j != i:
                soma += A[i][j] * x_ant[j]
        
        # Fórmula do método de Jacobi
        x_novo[i] = (B[i] - soma) / A[i][i]
    
    # Calcula o erro (diferença máxima entre iterações)
    erro = np.max(np.abs(x_novo - x_ant))
    
    # Mostra o progresso de cada iteração (6 casas)
    print(f"Iteração {k}: x = {x_novo.ravel()}, erro = {erro:.6f}")
    
    # Verifica o critério de parada
    if erro < e:
        break
    
    # Atualiza o vetor anterior
    x_ant = x_novo.copy()

# Exibe o resultado final
print("\nSolução aproximada encontrada:")
print(x_novo)
print(f"Número total de iterações: {k}")

Matriz A:
[[ 5. -2.  0. -1.]
 [ 1.  8.  2.  0.]
 [ 0.  3.  7. -2.]
 [ 0.  0.  3.  7.]]

Vetor B:
[[  2.]
 [-11.]
 [-27.]
 [ 29.]]

Chute inicial x0:
[[1.]
 [1.]
 [1.]
 [1.]]

Início do método de Gauss–Jacobi:

Iteração 1: x = [ 1.       -1.75     -4.        3.714286], erro = 5.000000
Iteração 2: x = [ 0.442857 -0.5      -2.045918  5.857143], erro = 2.142857
Iteração 3: x = [ 1.371429 -0.918878 -1.969388  5.019679], erro = 0.928571
Iteração 4: x = [ 1.036385 -1.054082 -2.029144  4.98688 ], erro = 0.335044
Iteração 5: x = [ 0.975743 -0.997262 -1.980571  5.01249 ], erro = 0.060641
Iteração 6: x = [ 1.003593 -1.001825 -1.997605  4.991673], erro = 0.027850
Iteração 7: x = [ 0.997605 -1.001048 -2.001597  4.998973], erro = 0.007300
Iteração 8: x = [ 0.999376 -0.999301 -1.999844  5.000684], erro = 0.001771
Iteração 9: x = [ 1.000416 -0.999961 -2.000104  4.999933], erro = 0.001041
Iteração 10: x = [ 1.000002 -1.000026 -2.000036  5.000045], erro = 0.000414

Solução aproximada encontrada:
[[ 1.00

In [3]:
#c) Método de Gauss–Seidel
# Gauss–Seidel Method
import numpy as np
np.set_printoptions(precision=6, suppress=True)

# Precisão desejada (erro máximo permitido)
e = 1e-3

# Chute inicial (4x1)
x = np.array([[1.0],
              [1.0],
              [1.0],
              [1.0]])

# Matriz dos coeficientes A (4x4)
A = np.array([
    [ 5., -2.,  0., -1.],
    [ 1.,  8.,  2.,  0.],
    [ 0.,  3.,  7., -2.],
    [ 0.,  0.,  3.,  7.]
], dtype=float)

# Vetor de termos independentes B (4x1)
B = np.array([
    [  2.],
    [-11.],
    [-27.],
    [ 29.]
], dtype=float)

# Número de variáveis (tamanho do sistema)
n = len(B)

# Contador de iterações
k = 0

while True:
    k += 1  
    x_ant = x.copy()
    
    for i in range(n):
        soma = 0.0
        
        for j in range(n):
            if j != i:
                soma += A[i][j] * x[j]  # usa valores já atualizados quando j<i
        
        x[i] = (B[i] - soma) / A[i][i]
    
    erro = np.max(np.abs(x - x_ant))
    
    print(f"Iteração {k}: x = {x.ravel()}, erro = {erro:.6f}")
    
    # Verifica o critério de parada
    if erro < e:
        break
    
# Exibe o resultado final
print("\nSolução aproximada encontrada:")
print(x)
print(f"Número total de iterações: {k}")

Iteração 1: x = [ 1.       -1.75     -2.821429  5.352041], erro = 4.352041
Iteração 2: x = [ 0.770408 -0.765944 -1.999727  4.999883], erro = 0.984056
Iteração 3: x = [ 1.093599 -1.011768 -1.99499   4.997853], erro = 0.323191
Iteração 4: x = [ 0.994863 -1.00061  -2.000352  5.000151], erro = 0.098736
Iteração 5: x = [ 0.999786 -0.999885 -2.000006  5.000003], erro = 0.004923
Iteração 6: x = [ 1.000046 -1.000004 -1.999997  4.999999], erro = 0.000260

Solução aproximada encontrada:
[[ 1.000046]
 [-1.000004]
 [-1.999997]
 [ 4.999999]]
Número total de iterações: 6
